[package]
name = "oc_email_stage1"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rsa = { version = "=0.9.8", default-features = false }
sha2 = { version = "=0.10.9", features = ["oid"] }
rand_core = "=0.6.4"
base64ct = { version = "=1.8.0", features = ["alloc"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
